## Strings

In [ ]:
#Ordered, immutable, text representation

my_string = "Hello Python"
char = my_string[0]
print(char)

my_string_2 = my_string[::-1]
print(my_string_2)

for x in my_string:
    print(x)
    
try:
    if 'o' in my_string:
        print(True)
except:
    print(False)
    
print(my_string.upper())
print(my_string.startswith("H"))
print(my_string.find("l"))
print(my_string.count("l"))
print(my_string.replace("Hello", "Goodbye"))

new_string = "Good, Afternoon"
new_string_2 = new_string.split(",")
print(new_string_2)

#Good way to take a list and convert back into a string
new_string = ' '.join(new_string_2)
print(new_string)

my_list = ['a'] * 6
print(my_list)

my_string = ' '.join(my_list)
print(my_string)

#Formatting strings

z = 'Mike'
my_string = 'The variable is %s' % z
print(my_string)

z = 10
my_string = 'The variable is %d' % z
print(my_string)

z = 'Mike'
my_string = 'The variable is {}'.format(z)
print(my_string)

z = 10
my_string = 'The variable is {}'.format(z)
print(my_string)

z = 'Mike'
my_string = f'The variable is {z}'
print(my_string)

z = 10
my_string = f'The variable is {z}'
print(my_string)

## Lists

In [ ]:
#Lists are ordered, mutable, & allows duplicate elements

my_list = ["cup", "spoon", "fork"]
print(my_list)

my_list2 = [5, False, "car", "car"]
print(my_list2)

item = my_list2[1]
print(item)

#Start from the end 
item = my_list2[-1]
print(item)

for x in item:
    print(x)
    
print(len(my_list))

#Add to a list
my_list.append("knife")
print(my_list)

#Insert value at certain position
my_list2.insert(2, True)
print(my_list2)

#Remove entry from list
my_list2.pop(3)

my_list.sort()
print(my_list)

#Concatenate 2 lists
new_list = my_list + my_list2
print(new_list)

#Slicing indexes
slice_list = [1, 2, 3, 4, 5, 6, 7]

x = slice_list[1:5]
print(x)

x = slice_list[0::2]
print(x)

#Reverse list
x = slice_list[::-1]
print(x)

#List comprehension
a = [1, 2, 3, 4, 5, 6, 7]
b = [i * i for i in a]

print(a)
print(b)

## Tuples

In [ ]:
#Ordered, immutable, allows duplicate elements
#Becuse of the immutable qualities, Python can optimize
#working with tuples. Tuples are better to work with 
#when there is a large amount of data

#Before we begin, let's validate the above statement

import sys

my_list = [0, 1, 2, 'x', 'y', 'z', 'Good Morning']
my_tuple = (0, 1, 2, 'x', 'y', 'x', 'Good Morning')

print(sys.getsizeof(my_list),'Bytes')
print(sys.getsizeof(my_tuple),'Bytes')

my_tuple = ("Mike", 36, "Knoxville")
            
item = my_tuple[2]
print(item)

#Tuple is immutable so this will not work
#my_tuple[2] = "Joseph"

if "Mike" in my_tuple:
    print(True)
    
new_tuple = ('b', 'i', 's', 'c', 'u', 'i', 't')

print(new_tuple.count('i'))
print(new_tuple.index('s'))

#Convert to list
new_list = list(my_tuple)
print(new_list)

a = (1, 2, 3, 4, 5, 6, 7, 8)
b = a[2:7:1]
print(b)

name, age, city = my_tuple
print(name)
print(age)
print(city)

#Shortcut to unpack using *

i1, *i2, i3 = new_tuple
print(i1)
print(i2)
print(i3)


## Dictionaries

In [ ]:
#Key-Value pairs, unordered, mutable

my_dict = {"Name": "Mike", "Age": 36, "City": "Knoxville"}
print(my_dict)
print(my_dict["Age"])

value = my_dict["Name"]
print(value)

my_dict["E-mail"] = "mike@xyzabc.com"
print(my_dict)

del my_dict["E-mail"]
print(my_dict)

#my_dict.pop("Name")
#print(my_dict)

#Check to see if Key is in dictionary
if "Name" in my_dict:
    print(my_dict["Name"])
    
try:
    print(my_dict["Last_Name"])
except:
    print("Error")
    
#Iterate through

for key in my_dict:
    print(key)
#Another way

for key in my_dict.keys():
    print(key)
    
for key, value in my_dict.items():
    print(key, value)
    


## Sets

In [ ]:
#Unordered, mutable, no duplicates

my_set = {'a', 'b', 'c', 'd', 'f', 'g'}
print(my_set)

my_set.add(1)
my_set.add(2)
my_set.add(3)
print(my_set)

my_set.discard(3)
print(my_set)

for i in my_set:
    print(i)
    
odds = {1, 3, 5, 7, 9}
evens = {0, 2, 4, 6, 8}
primes = {2, 3, 5, 7}

u = odds.union(evens)
print(u)

i = odds.intersection(evens)
print(i)

i = odds.intersection(primes)
print(i)

i = evens.intersection(primes)
print(i)

setA = {1, 2, 3, 4, 5, 6, 7, 8, 9}
setB = {1, 2, 3, 10, 11, 12}
setC = {1, 2, 3}

diff = setA.difference(setB)
print(diff)

diff = setB.symmetric_difference(setA)
print(diff)

print(setA.issubset(setB))
print(setC.issubset(setB))

#Frozen set

x = frozenset([1, 2, 3])

#Cannot modify after creation of frozen set
x.add(2)
print(a)

## Collections

In [90]:
#Counter, namedtuple, OrderedDict, defaultdict, deque

from collections import Counter
from collections import namedtuple 
from collections import OrderedDict
from collections import defaultdict
from collections import deque 

x = 'qqqqqqwwwwwwwweeeeeeeee'
my_counter = Counter(x)
print(my_counter)

#How many of each element
print(my_counter.values())

#Most common element
print(my_counter.most_common(1))

print(list(my_counter.elements()))

#Create a class with namedtuple called Bucket with values a & b
Bucket = namedtuple('Bucket', 'a, b')

#Add values to a & b
bckt = Bucket(-10, 10)
print(bckt)

#Ordered dict will hold values & key in memory as inputted
ordered_dict = OrderedDict()
ordered_dict['a'] = 1
ordered_dict['b'] = 2
ordered_dict['c'] = 3
ordered_dict['d'] = 4

print(ordered_dict)

ordered_dict['c'] = 3
ordered_dict['d'] = 4
ordered_dict['a'] = 1
ordered_dict['b'] = 2

print(ordered_dict)

d = defaultdict(int)
d['a'] = 1
d['b'] = 2
print(d['a'])

d = deque()

d.append(1)
d.append(2)
d.appendleft(3)
print(d)

d.pop()
d.popleft()
print(d)

d.extend([4, 5, 6])
print(d)

d.rotate(2)
print(d)

Counter({'e': 9, 'w': 8, 'q': 6})
dict_values([6, 8, 9])
[('e', 9)]
['q', 'q', 'q', 'q', 'q', 'q', 'w', 'w', 'w', 'w', 'w', 'w', 'w', 'w', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e']
Bucket(a=-10, b=10)
OrderedDict([('a', 1), ('b', 2), ('c', 3), ('d', 4)])
OrderedDict([('a', 1), ('b', 2), ('c', 3), ('d', 4)])
1
deque([3, 1, 2])
deque([1])
deque([1, 4, 5, 6])
deque([5, 6, 1, 4])


## Itertools

In [110]:
#Itertools: product, permutations, combinations, accumulate, groupby
#and infinite iterators

from itertools import product
from itertools import permutations
from itertools import combinations
from itertools import accumulate
from itertools import groupby
import operator

x = [1, 2]
y = [3, 4]

prod = product(x, y)
print(prod)
print(list(prod))

a = [1, 2, 3]
perm = permutations(a)
#Can also add a number in permutations for a specified length
#perm = permutations(a, 2)
print(list(perm))

#Combinations

comb = combinations(a, 2)
print(list(comb))

#The function above will not show repetitious results:
# import combinations, combinations_with_replacement
#comb = combinations_with_replacements(a, 2)

#Groupby

def smaller_than_5(x):
    return x < 5

a = [1, 2, 3, 4, 5, 6]
group_obj = groupby(a, key = smaller_than_5)
try:
    for key, value in group_obj:
        print(key, list(value))
except:
    print(False, list(value))
    
#We can also use the lambda function

def smaller_than_5(x):
    return x < 5

a = [1, 2, 3, 4, 5, 6]
group_obj = groupby(a, key = lambda x: x<5)
try:
    for key, value in group_obj:
        print(key, list(value))
except:
    print(False, list(value))

#Accumulate

a = [1, 2, 3, 4]
accum = accumulate(a)
print(a)
print(list(accum))

#Accumulate by default computes the sums
#We can multiply by using the operator

accum = accumulate(a, func = operator.mul)
print(a)
print(list(accum))

[(1, 3), (1, 4), (2, 3), (2, 4)]
[(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]
[(1, 2), (1, 3), (2, 3)]
True [1, 2, 3, 4]
False [5, 6]
True [1, 2, 3, 4]
False [5, 6]
[1, 2, 3, 4]
[1, 3, 6, 10]
[1, 2, 3, 4]
[1, 2, 6, 24]


## Lambda

In [121]:
# Lambda is an anonymous one line function

add = lambda x: x + 10
print(add(5))

#This is the same as:

def add_func(x):
    return x + 10

multiply = lambda x, y: x + y
print(multiply(2, 7))

example = [(1, 2), (12, -1), (6, 8), (-1, -9)]
example_sorted = sorted(example)

print(example)
print(example_sorted)

example = [(1, 2), (12, -1), (6, 8), (-1, -9)]
#Using lambda we can sort using the second element
example_sorted = sorted(example, key = lambda x: x[1])

print(example)
print(example_sorted)

#Sort by each tuples sum
example_sorted = sorted(example, key = lambda x: x[0]+ x[1])
print(example_sorted)

#Map takes a function and applies it to each element
a = [1, 2, 3, 4, 5]

b = map(lambda x: x + 2, a)
print(list(b))

#List comprehension also can do the same
#b = [x + 2 for x in a]

from functools import reduce

product_a = reduce(lambda x, y: x * y, a)
print(product_a)

15
9
[(1, 2), (12, -1), (6, 8), (-1, -9)]
[(-1, -9), (1, 2), (6, 8), (12, -1)]
[(1, 2), (12, -1), (6, 8), (-1, -9)]
[(-1, -9), (12, -1), (1, 2), (6, 8)]
[(-1, -9), (1, 2), (12, -1), (6, 8)]
[3, 4, 5, 6, 7]
120


## Errors & Exceptions

In [130]:
#Python has many errors & exceptions from file handling to syntax errors.
#We can also make our own.

# x = -5
# if x < 0:
#     raise Exception('X Should be positive')
    
# Or

# x = -5
# assert (x >= 0), 'X is not positive'

try:
    a = 5 / 1
except Exception as e:
    print(e)
else:
    print('No errors found')
finally:
    print('Thank you for inputting your values correctly')
    
class ValueTooHighError(Exception):
    pass

def value(x):
    if x > 100:
        raise ValueTooHighError('Value is too high')


value(300)

No errors found
Thank you for inputting your values correctly


ValueTooHighError: Value is too high

## Logging

In [139]:
# Logging allows writing status messages to a file or any other output streams. 
# The file can contain the information on which part of the code is executed and 
# what problems have been arisen.
# By logging useful data from the right places, you can not only debug errors 
# easily, but also use the data to analyze the performance of the application 
# to plan for scaling or look at usage patterns to plan for marketing.

import logging

logging.basicConfig(level = logging.DEBUG, format = '%(asctime)s - %(name)s - %(levelname)s - %(message)s', 
                    datefmt = '%d/%m/%Y %H:%M:%S')

logging.debug('This is a debut message')
logging.info('This is an info message')
logging.warning('This is a warning message')
logging.error('This is an error message')
logging.critical('This is a critical message')

#Please reference the logging folder for additional code 

'''Notebook continues here'''

# Traceback
try:
    a = [1, 2, 3]
    val = a[4]
except IndexError as e:
    logging.error(e, exc_info = True)



12/01/2023 19:22:03 - root - DEBUG- This is a debut message
12/01/2023 19:22:03 - root - INFO- This is an info message
12/01/2023 19:22:03 - root - WARNING- This is a warning message
12/01/2023 19:22:03 - root - ERROR- This is an error message
12/01/2023 19:22:03 - root - CRITICAL- This is a critical message
12/01/2023 19:22:03 - root - ERROR- list index out of range
Traceback (most recent call last):
  File "/tmp/ipykernel_592024/622534419.py", line 25, in <module>
    val = a[4]
IndexError: list index out of range


## Random Numbers

In [163]:
# Random has many uses in statistics, cryptography, gaming, gambling, and other fields.

import random
import secrets

a = random.randrange(1, 10)
print(a)


a = random.normalvariate(1, 1)
print(a)

my_list = list("QWERTY")
a = random.choices(my_list, k = 3)
print(a)

random.shuffle(my_list)
print(my_list)

a = secrets.randbits(4)
print(a)

import numpy as np

x = np.random.rand(3, 3)
print(x)

np.random.shuffle(x)
print(x)

7
0.8729643407276467
['W', 'T', 'W']
['W', 'E', 'R', 'T', 'Q', 'Y']
10
[[0.83866386 0.16201587 0.46596908]
 [0.94950908 0.25908599 0.24947712]
 [0.71514201 0.13308715 0.79629223]]
[[0.83866386 0.16201587 0.46596908]
 [0.71514201 0.13308715 0.79629223]
 [0.94950908 0.25908599 0.24947712]]


## JSON

In [147]:
# JavaScript Object Notation
# JSON is a standard text-based format for representing structured data 
# based on JavaScript object syntax. It is commonly used for transmitting 
# data in web applications (e.g., sending some data from the server to the client,
# so it can be displayed on a web page, or vice versa)

import json

individual = {"name": "David", "age": 30, "city": "Knoxville",
              "has_children": False, "titles": ["programmer",
                                                "data analyst"]}
individual_JSON = json.dumps(individual)

print(individual_JSON)

individual_JSON = json.dumps(individual, indent = 4, sort_keys = True)
#dumps, s = string

print(individual_JSON)

with open('individual.JSON', 'w') as file:
           json.dump(individual, file, indent = 4)
        
# Convert from JSON back to dictionary
with open('individual.JSON', 'r') as file:
    individual = json.loads(individual_JSON)
    print(individual)

{"name": "David", "age": 30, "city": "Knoxville", "has_children": false, "titles": ["programmer", "data analyst"]}
{
    "age": 30,
    "city": "Knoxville",
    "has_children": false,
    "name": "David",
    "titles": [
        "programmer",
        "data analyst"
    ]
}
{'age': 30, 'city': 'Knoxville', 'has_children': False, 'name': 'David', 'titles': ['programmer', 'data analyst']}
